```mermaid
flowchart TD
  subgraph AdminStoreDashboard["店舗ダッシュボードフロー"]
    SD0["店舗ダッシュボード"]

    %% 店舗レイアウト設定
    SD0 --> SD10["店舗レイアウト設定"]
    subgraph Layout["店舗レイアウト設定"]
      SD10 --> SD101["座席属性設定"]
      SD101 --> SD1011["座席属性作成"]
      SD101 --> SD1012["座席属性編集"]
      SD10 --> SD102["座席設定"]
      SD102 --> SD1021["座席作成"]
      SD102 --> SD1022["座席編集"]
      SD10 --> SD103["店舗レイアウト設定"]
      SD103 --> SD1031["店舗レイアウト作成"]
      SD103 --> SD1032["店舗レイアウト編集"]
      SD1031 --> SD1021
    end

    %% 営業日/休業日設定
    SD0 --> SD20["営業日/休業日設定"]
    subgraph BusinessDays["営業日/休業日設定"]
      SD20 --> SD201["営業日設定"]
      SD201 --> SD2011["営業日作成"]
      SD20 --> SD202["定休日設定"]
      SD202 --> SD2021["定休日作成"]
      SD20 --> SD203["臨時営業日/休業日設定"]
      SD203 --> SD2031["臨時営業日・休業日設定"]
    end

    %% コース設定
    SD0 --> SD30["コース設定"]
    subgraph Course["コース設定"]
      SD30 --> SD301["コース設定"]
      SD301 --> SD3011["コース作成"]
      SD301 --> SD3012["コース編集"]
      SD30 --> SD302["材料設定"]
      SD302 --> SD3021["材料作成"]
    end

    %% カレンダー／予約確認
    SD0 --> SD40["カレンダー"]
    SD40 --> SD401["予約リスト・検索"]
    SD40 --> SD402["日別予約ビュー"]
    SD40 --> SD404["予約手動追加"]
    SD40 --> SD2031
    SD401 --> SD403["予約詳細画面"]
    SD402 --> SD403

    %% レポート
    SD0 --> SD60["レポート"]
    subgraph Reports["レポート"]
      SD60 --> SD601["売上予測"]
      SD60 --> SD602["発注予測"]
    end

    %% 各種設定
    SD0 --> SD70["各種設定"]
    subgraph Settings["各種設定"]
      SD70 --> SD701["店舗情報設定"]
      SD70 --> SD702["予約設定"]
    end
  end

```
