```mermaid

flowchart TD
  subgraph AdminFlow["管理画面フロー"]
    A1["管理画面ログイン"]
    A1 -- 認証成功 --> D1{ユーザーロール判定}
    D1 -- オーナー --> A2["オーナーダッシュボード"]
    D1 -- 店長・スタッフ --> C2["店舗管理画面"]

    A2 --> B1["システム管理"]
    A2 --> B2["店舗管理"] -- 各店舗の設定へ --> C2[”店舗管理画面”]
    A2 --> B3["ユーザー管理"]
  end

```